apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: styleguide
  description: VTEX Styleguide React components
  tags:
    - typescript
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/styleguide
    vtex.com/platform-flow-id: CommDev#2,Merch#3
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: T0WTW0H3
    vtex.com/sdd-check-skip: 'true'
    vtex.com/sdd-check-skip-reason: The styleguide is a shared UI component library and doesn't require a Service Design Document. This component is deprecated and no longer under active development.
spec:
  lifecycle: stable
  owner: te-0013
  type: library
  dependsOn: []
