export default {
  TABLE_HEADER_HEIGHT: 36,
  EMPTY_STATE_SIZE_IN_ROWS: 5,
  DEFAULT_SCROLLBAR_WIDTH: 17,
  DENSITY_OPTIONS: ['low', 'medium', 'high'],
  FIELDS_BOX_ITEM_HEIGHT: 36,
  MEDIUM_ICON_SIZE: 14,
}
