export const TABLE_DENSITIES = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
}
export const TABLE_HEADER_HEIGHT = 36
export const EMPTY_STATE_SIZE_IN_ROWS = 5
export const DEFAULT_SCROLLBAR_WIDTH = 17
export const FIELDS_BOX_ITEM_HEIGHT = 36
export const MEDIUM_ICON_SIZE = 14
export const DENSITY_OPTIONS = [
  TABLE_DENSITIES.LOW,
  TABLE_DENSITIES.MEDIUM,
  TABLE_DENSITIES.HIGH,
]
export const COLLAPSIBLE_ROW_PREFIX_WIDTH = 36
