export const products = [
  {
    id: 1,
    name: 'Macbook Pro 13 inch',
    categories: ['laptop'],
    manufacturer: 'apple',
    qty: 200,
    costPrice: 800,
    retailPrice: 1299,
    wholesalePrice: 1000,
  },
  {
    id: 2,
    name: 'Pixel 4',
    categories: ['smartphone'],
    manufacturer: 'google',
    qty: 100,
    costPrice: 600,
    retailPrice: 799,
    wholesalePrice: 700,
  },
  {
    id: 3,
    name: 'Macbook Pro 16 inch',
    categories: ['laptop'],
    manufacturer: 'apple',
    qty: 10,
    costPrice: 1800,
    retailPrice: 2399,
    wholesalePrice: 2000,
  },
  {
    id: 4,
    name: 'Ipad Pro 12.9 inch',
    categories: ['tablet'],
    manufacturer: 'apple',
    qty: 210,
    costPrice: 600,
    retailPrice: 999,
    wholesalePrice: 750,
  },
  {
    id: 5,
    name: 'XPS 15',
    categories: ['laptop'],
    manufacturer: 'dell',
    qty: 500,
    costPrice: 500,
    retailPrice: 1050,
    wholesalePrice: 950,
  },
  {
    id: 6,
    name: 'Disabled Item',
    categories: ['laptop'],
    manufacturer: 'example',
    qty: 0,
    costPrice: 500,
    retailPrice: 1050,
    wholesalePrice: 950,
  },
  {
    id: 7,
    name: 'IPhone 11 Pro',
    categories: ['smartphone'],
    manufacturer: 'apple',
    qty: 450,
    costPrice: 700,
    retailPrice: 1100,
    wholesalePrice: 950,
  },
]

export const payments = [
  {
    icon: 'FaCcPaypal',
    id: '1',
    name: 'Paypal',
    status: 'ACTIVE',
  },
  {
    icon: 'FaCcMastercard',
    id: '2',
    name: 'Mastercard',
    status: 'ACTIVE',
  },
  {
    icon: 'FaCcDinersClub',
    id: '3',
    name: 'Dinners Club',
    status: 'ACTIVE',
  },
  {
    icon: 'FaCcDiscover',
    id: '4',
    name: 'Discover',
    status: 'INACTIVE',
  },
  {
    icon: 'FaCcAmazonPay',
    id: '5',
    name: 'Amazon Pay',
    status: 'INACTIVE',
  },
  {
    icon: 'FaCcApplePay',
    id: '6',
    name: 'Apple Pay',
    status: 'ACTIVE',
  },
  {
    icon: 'FaCcVisa',
    id: '7',
    name: 'Visa',
    status: 'ACTIVE',
  },
  {
    icon: 'FaCcAmex',
    id: '8',
    name: 'American Express',
    status: 'INACTIVE',
  },
]
