/* eslint-disable */
import React from 'react'
export default {
  defaultSchema: {
    properties: {
      name: {
        type: 'string',
        title: 'Name',
      },
      email: {
        type: 'string',
        format: 'email',
        title: 'Email',
        width: 350,
      },
      number: {
        type: 'number',
        title: 'Number',
      },
    },
  },
  customSchema: {
    properties: {
      name: {
        type: 'string',
        title: 'Name',
      },
      email: {
        type: 'string',
        format: 'email',
        title: 'Email',
        width: 350,
        cellRenderer: ({ cellData }) => <button>{cellData}</button>,
      },
      number: {
        type: 'number',
        title: 'Number',
        headerRenderer: () => <button>custom component</button>,
      },
    },
  },
  items: [
    {
      email: 'Olen.Stamm21@yahoo.com',
      name: 'Ms. Christophe Legros',
      number: 52725,
      index: 0,
    },
    {
      email: 'Junius0@gmail.com',
      name: 'Sierra Donnelly IV',
      number: 84639,
      index: 1,
    },
    {
      email: 'Hailee.Botsford24@gmail.com',
      name: 'Mr. Ron Smith',
      number: 23851,
      index: 2,
    },
    {
      email: 'Judd_Gulgowski22@yahoo.com',
      name: 'Braeden Abernathy',
      number: 10182,
      index: 3,
    },
    {
      email: 'Gaetano.Mayert71@yahoo.com',
      name: 'Norris Murazik',
      number: 33725,
      index: 4,
    },
    {
      email: 'Catharine.Leuschke62@hotmail.com',
      name: 'Kristopher Boyle',
      number: 33245,
      index: 5,
    },
    {
      email: 'Candido_Ryan@hotmail.com',
      name: 'Isaac Mayert I',
      number: 96637,
      index: 6,
    },
    {
      email: 'Freda_Ritchie26@yahoo.com',
      name: 'Dr. Lempi Mosciski',
      number: 42623,
      index: 7,
    },
    {
      email: 'Elissa28@gmail.com',
      name: 'Nikita Feeney',
      number: 11769,
      index: 8,
    },
    {
      email: 'Reginald1@yahoo.com',
      name: 'Janick Lesch',
      number: 85311,
      index: 9,
    },
    {
      email: 'Jerad_Hyatt@hotmail.com',
      name: 'Golda Carter',
      number: 44288,
      index: 10,
    },
    {
      email: 'Jaquan.Fisher61@yahoo.com',
      name: 'Dr. Cassandra Jerde',
      number: 73372,
      index: 11,
    },
    {
      email: 'Marlee_Ziemann@yahoo.com',
      name: 'Bethel Kshlerin',
      number: 62416,
      index: 12,
    },
    {
      email: 'German_Beier@yahoo.com',
      name: 'Arch Hegmann',
      number: 82120,
      index: 13,
    },
    {
      email: 'Arturo_Schroeder30@yahoo.com',
      name: 'Alessandro Strosin',
      number: 73701,
      index: 14,
    },
    {
      email: 'Santos_Doyle36@gmail.com',
      name: 'Zander Vandervort',
      number: 26124,
      index: 15,
    },
    {
      email: 'Yvonne.Gleason@hotmail.com',
      name: 'Lorena Balistreri',
      number: 79484,
      index: 16,
    },
    {
      email: 'Michaela51@hotmail.com',
      name: 'Emanuel Ullrich',
      number: 57879,
      index: 17,
    },
    {
      email: 'Erik_Kuvalis41@hotmail.com',
      name: 'Robyn Aufderhar',
      number: 87262,
      index: 18,
    },
    {
      email: 'Edwardo_Kuvalis@hotmail.com',
      name: 'Mrs. Deion Beahan',
      number: 13464,
      index: 19,
    },
    {
      email: 'Alexa_Ondricka45@hotmail.com',
      name: 'Trent Kerluke',
      number: 9677,
      index: 20,
    },
    {
      email: 'Darron_Brakus63@yahoo.com',
      name: 'Jacquelyn Flatley Jr.',
      number: 55405,
      index: 21,
    },
    {
      email: 'Jamie.Hermann60@gmail.com',
      name: 'Ervin Kuphal',
      number: 76965,
      index: 22,
    },
    {
      email: 'Cleo.Klein@hotmail.com',
      name: 'Terrence Gutmann',
      number: 55731,
      index: 23,
    },
    {
      email: 'Alicia.Ullrich@yahoo.com',
      name: 'Oren Beatty V',
      number: 6073,
      index: 24,
    },
    {
      email: 'Maynard.Kulas@hotmail.com',
      name: 'Dr. Colby Gottlieb',
      number: 27670,
      index: 25,
    },
    {
      email: 'Madonna_Feeney@yahoo.com',
      name: 'Ernestina Rempel',
      number: 75422,
      index: 26,
    },
    {
      email: 'Pearlie_Ondricka@hotmail.com',
      name: 'Kathryne Graham',
      number: 46363,
      index: 27,
    },
    {
      email: 'Elise21@yahoo.com',
      name: 'Cecelia Marquardt',
      number: 49598,
      index: 28,
    },
    {
      email: 'Willis.Cremin@hotmail.com',
      name: 'Bradford Stanton',
      number: 21061,
      index: 29,
    },
    {
      email: 'Marcus31@gmail.com',
      name: 'Zachary Bednar',
      number: 35011,
      index: 30,
    },
    {
      email: 'Morris15@gmail.com',
      name: 'Roxanne Kozey',
      number: 54952,
      index: 31,
    },
    {
      email: 'Marge_Veum47@hotmail.com',
      name: 'Amelia Gutmann',
      number: 41825,
      index: 32,
    },
    {
      email: 'Zack27@gmail.com',
      name: 'Armani Kuhic',
      number: 230,
      index: 33,
    },
    {
      email: 'Betty.Pouros48@hotmail.com',
      name: 'Antonietta Koch',
      number: 62524,
      index: 34,
    },
    {
      email: 'Soledad.Huel@gmail.com',
      name: 'Pansy Kuphal',
      number: 3655,
      index: 35,
    },
    {
      email: 'Vaughn_Huel42@yahoo.com',
      name: 'Brody Mohr',
      number: 70076,
      index: 36,
    },
    {
      email: 'Thurman24@gmail.com',
      name: 'Gustave Grady',
      number: 32633,
      index: 37,
    },
    {
      email: 'Antonette.Aufderhar@hotmail.com',
      name: 'Ms. Neva Thompson',
      number: 15857,
      index: 38,
    },
    {
      email: 'Ryan_Kub@gmail.com',
      name: 'Clarissa Boyer',
      number: 46555,
      index: 39,
    },
    {
      email: 'Mable_Wilkinson24@hotmail.com',
      name: 'Marcelle Orn',
      number: 19603,
      index: 40,
    },
    {
      email: 'Adeline36@yahoo.com',
      name: 'Domenico Olson V',
      number: 37333,
      index: 41,
    },
    {
      email: 'Arno.Hegmann@gmail.com',
      name: 'Ms. Marcos Bechtelar',
      number: 82189,
      index: 42,
    },
    {
      email: 'Israel.Boyle2@gmail.com',
      name: 'Devon Mante',
      number: 27772,
      index: 43,
    },
    {
      email: 'Maxime.Auer@hotmail.com',
      name: 'Isabelle Keeling',
      number: 94458,
      index: 44,
    },
    {
      email: 'Jalen.Schmeler7@yahoo.com',
      name: 'Francisco Rodriguez',
      number: 89358,
      index: 45,
    },
    {
      email: 'Robin_Dach43@gmail.com',
      name: 'Destany Farrell',
      number: 67488,
      index: 46,
    },
    {
      email: 'Sid64@gmail.com',
      name: 'Miss Haylee Sporer',
      number: 11384,
      index: 47,
    },
    {
      email: 'Barney_Batz85@gmail.com',
      name: 'Alisa Bayer',
      number: 25164,
      index: 48,
    },
    {
      email: 'Darien.Yundt66@gmail.com',
      name: 'Bernhard Weissnat',
      number: 39351,
      index: 49,
    },
  ],
}
